name: pitch_me_app
description: A new Flutter project.

publish_to: "none" 

version: 1.0.5+6

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.3
  get: ^4.6.5
  swipable_stack: ^2.0.0
  google_fonts: ^4.0.1
  responsive_framework: ^1.0.0
  video_viewer:
    path: packages/video_viewer-1.2.7
  cached_network_image: ^3.2.2
  shared_preferences: ^2.0.15
  firebase_core: ^2.4.1
  google_sign_in: ^6.1.3
  firebase_auth: ^4.2.4
  fluttertoast: ^8.2.2
  flutter_facebook_auth: ^5.0.11
  sign_in_with_apple: ^4.1.0
  visibility_detector: ^0.4.0+2
  smooth_star_rating_null_safety: ^1.0.4+2
  # provider: ^6.0.5
  flutter_widget_from_html: ^0.10.3
  #shimmer: ^3.0.0
  #flutter_inset_box_shadow: ^1.0.8
  #flutter_neumorphic: ^3.1.0
  #swipeable_card_stack: ^0.0.5
  #never_behind_keyboard: ^1.0.1
  #video_viewer: ^1.2.0
  #get_storage: ^2.0.2
  #media_info: ^0.12.0+1
  
#dev
  sizer: ^2.0.15
  clickable_list_wheel_view: ^0.2.0
  percent_indicator: ^4.2.2
  google_places_flutter: ^2.0.5
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  image_pickers: ^2.0.0+6
  image_picker: ^0.8.7+4
  camera: ^0.10.5+2
  path_provider: ^2.0.11
  intl: ^0.18.1  
  chips_choice: ^3.0.0
  url_launcher: ^6.1.7
  permission_handler: ^10.2.0
  # record: ^4.4.4
  voice_message_package: ^1.0.41
  syncfusion_flutter_signaturepad: ^20.4.54
  socket_io_client: ^2.0.2
  firebase_storage: ^11.2.3
  flutter_beep: ^1.0.0
  share_plus: ^6.3.4
  flutter_inappwebview: ^5.7.2+3
  image_gallery_saver: ^2.0.3
  flutter_document_picker: ^5.2.3
  record: ^5.0.4
  # voice_message_package: ^2.1.0
  
  
dependency_overrides:
  video_player: ^2.3.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imagess/avatar.png"
  flutter_test:
    sdk: flutter
  get_cli: ^1.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/images/
    - assets/icons/
    - assets/Phase 2 icons/
    - assets/imagess/
  fonts:
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/proxima/Fontspring-DEMO-proximanova-thin.otf
          weight: 100
        - asset: assets/fonts/proxima/Fontspring-DEMO-proximanovaexcn-light.otf
          weight: 200
        - asset: assets/fonts/proxima/Fontspring-DEMO-proximanovaexcn-light.otf
          weight: 300
        - asset: assets/fonts/proxima/Fontspring-DEMO-proximanova-regular.otf
          weight: 400
        - asset: assets/fonts/proxima/Fontspring-DEMO-proximanova-medium.otf
          weight: 500
        - asset: assets/fonts/proxima/Fontspring-DEMO-proximanova-semibold.otf
          weight: 600
        - asset: assets/fonts/proxima/Fontspring-DEMO-proximanova-bold.otf
          weight: 700
        - asset: assets/fonts/proxima/Fontspring-DEMO-proximanova-extrabold.otf
          weight: 800
        - asset: assets/fonts/proxima/Fontspring-DEMO-proximanovacond-black.otf
          weight: 900

  